# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  # - release
  - 0.7
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0

# To build on trusty, need this (see https://github.com/JuliaIO/HDF5.jl/issues/446)
sudo: required
